#!/sh


addgroup -S nginx
adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx

apk add --no-cache --virtual .build-deps \
    build-base \
    curl \
    gd-dev \
    geoip-dev \
    libxslt-dev \
    linux-headers \
    make \
    perl-dev \
    readline-dev \
    zlib-dev \
    pcre-dev \
    gnupg \
    openssl-dev \
    unzip

export NAXSI_VERSION=$(curl -s https://api.github.com/repos/nbs-system/naxsi/releases/latest | grep 'tag_name' | cut -d\" -f 4)
#export NGINX_VERSION=$(curl -s https://raw.githubusercontent.com/nginxinc/docker-nginx/master/stable/alpine/Dockerfile | grep "ENV.*NGINX_VERSION" | cut -d" " -f3)
export RESTY_VERSION=$(curl -s https://api.github.com/repos/openresty/openresty/releases/latest | grep 'tag_name' | cut -d\" -f 4)
export RESTY_VERSION=${RESTY_VERSION:1}
export _RESTY_CONFIG_DEPS=""

export RESTY_CONFIG_OPTIONS=" --add-module=/tmp/naxsi-$NAXSI_VERSION/naxsi_src  $RESTY_CONFIG_OPTIONS "

mkdir -p /usr/src /etc/nginx/naxsi
cd /tmp
curl -fSL https://github.com/nbs-system/naxsi/archive/$NAXSI_VERSION.tar.gz -o naxsi-$NAXSI_VERSION.tar.gz \
&& tar xzf naxsi-${NAXSI_VERSION}.tar.gz \
&& curl -fSL https://github.com/openresty/openresty/releases/download/v${RESTY_VERSION}/openresty-${RESTY_VERSION}.tar.gz -o openresty-${RESTY_VERSION}.tar.gz \
&& tar xzf openresty-${RESTY_VERSION}.tar.gz \
&& cd /tmp/openresty-${RESTY_VERSION} \
&& ./configure -j$(getconf _NPROCESSORS_ONLN) ${_RESTY_CONFIG_DEPS} ${RESTY_CONFIG_OPTIONS} \
&& make -j$(getconf _NPROCESSORS_ONLN) \
&& make -j$(getconf _NPROCESSORS_ONLN) install \
&& mv /usr/local/openresty/nginx/conf /etc/nginx/ \
&& mkdir -p /etc/nginx/conf.d/ \
&& mkdir -p /usr/share/nginx && ln -s /usr/local/openresty/nginx/html /usr/share/nginx/html \
&& ln -sf /etc/nginx /usr/local/openresty/nginx/conf \
&& ln -sf /usr/local/openresty/nginx/sbin/nginx /usr/sbin/nginx \
&& mkdir -p /usr/lib/nginx \
&& ln -sf /usr/local/openresty/nginx/modules /usr/lib/nginx/modules \
&& ln -s ../../usr/local/openresty/nginx/modules /etc/nginx/modules \
&& cd /tmp && cp -a /tmp/naxsi-$NAXSI_VERSION/naxsi_config/* /etc/nginx/naxsi/ \
&& curl -fSL https://github.com/nbs-system/naxsi-rules/archive/master.zip -o naxsi-rules.zip \
&& unzip naxsi-rules.zip && mv naxsi-rules-master /etc/nginx/naxsi/rules \
&& strip /usr/local/openresty/nginx/sbin/nginx* \
&& strip /usr/lib/nginx/modules/*.so \
&& cd /tmp && rm -rf * \
&& rm -rf /usr/local/openresty/pod /usr/local/openresty/luajit/include \
   # Bring in gettext so we can get `envsubst`, then throw
  	# the rest away. To do this, we need to install `gettext`
  	# then move `envsubst` out of the way so `gettext` can
  	# be deleted completely, then move `envsubst` back.
  	apk add --no-cache --virtual .gettext gettext \
   && mv /usr/bin/envsubst /tmp/ \
  	\
  	&& runDeps="$( \
  		scanelf --needed --nobanner   /usr/local/openresty/lualib/*/*.so /usr/local/openresty/lualib/*.so /usr/local/openresty/*/lib/* /usr/local/openresty/bin/* /usr/lib/nginx/modules/*.so /tmp/envsubst \
  			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
  			| sort -u \
  			| xargs -r apk info --installed \
  			| sort -u \
  	)" \
  	&& apk add --no-cache --virtual .nginx-rundeps $runDeps \
  	&& apk del --no-cache .build-deps \
  	&& apk del --no-cache .gettext \
  	&& mv /tmp/envsubst /usr/local/bin/ \
   && rm -rf  /usr/local/openresty/nginx/logs \
   && ln -sf /var/log/nginx /usr/local/openresty/nginx/logs \
   && ln -sf /var/run/nginx.pid /usr/local/openresty/nginx/logs/nginx.pid \
   && ln -sf /var/run/nginx.lock /usr/local/openresty/nginx/logs/nginx.lock \
   && mkdir -p /var/cache && ln -sf /tmp /var/cache/nginx/ \
  	&& ln -sf /dev/stdout /var/log/nginx/access.log \
  	&& ln -sf /dev/stderr /var/log/nginx/error.log
