apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Ngnix
  name: nginx
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and serve static content via NGINX.
      iconClass: icon-apache
      openshift.io/display-name: Nginx + Openresty
      sampleRepo: https://github.com/openshift/httpd-ex.git
      supports: httpd
      tags: builder,httpd,nginx
      version: "latest"
    from:
      kind: DockerImage
      name: oondeo/openresty:jessie
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
